name: automated_video_branding_tool_env
channels:
  - conda-forge
dependencies:
  - ffmpeg-python
  - imagemagick
  - python-dotenv
  - termcolor
  - moviepy
  - pip
  - pip:
    - gizeh
    - opencv-python
    - oauthlib
    - requests_oauthlib
    - boto3
    - youtube_dl
    - ffprobe-python