name: automated_video_branding_tool_env
channels:
  - anaconda
  - conda-forge
dependencies:
  - pandas
  - ffmpeg-python
  - imagemagick
  - python-dotenv
  - termcolor
  - pip
  - pip:
    - moviepy
    - gizeh
    - opencv-python
    - oauthlib
    - requests_oauthlib
    - boto3
    - youtube_dl
    - ffprobe-python