name: automated-editor
channels:
  - anaconda
  - conda-forge
dependencies:
  - pandas
  - ffmpeg-python
  - imagemagick
  - python-dotenv
  - termcolor
  - pip
  - gspread
  - oauth2client
  - pip:
    - moviepy
    - gizeh
    - opencv-python
    - oauthlib
    - requests_oauthlib
    - boto3
    - youtube_dl
    - ffprobe-python